name: pytest-coverage-commentator
on:
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    - name: Package install
      run: |
        pip install .
    - name: Install mkdoc dependencies
      run: |
        pip install .[docs]
    - name: Mkdocs build
      run: |
        mkdocs build -d doc-build
    - name: Install test dependencies
      run: |
        pip install .[tests]
    - name: Tests and coverage file
      run: |
        pytest --cache-clear --cov=rsm . > pytest-coverage.txt
    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2
