name: pytest-coverage-commentator
on:
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Update pipe
      run: |
        python -m pip install --upgrade pip
    - name: Install test dependencies
      run: |
        pip install .[tests]
    - name: Tests and coverage file
      run: |
        pytest --cache-clear --cov=rsm test/ > pytest-coverage.txt
    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2
    - name: Install mkdoc dependencies
      run: |
        pip install .[docs]
    - name: Mkdocs build
      run: |
        mkdocs build -d doc-build
