name: full build
on:
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: mirromutth/mysql-action@v1.1
      with:
        character set server: 'utf8'
        collation server: 'utf8_general_ci'
        mysql version: '8.0'
        mysql root password: ${{ secrets.MYSQL_ROOT }}
        mysql database: 'integration_test'
    # checkout after DB setup to minimise wasted time
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    - name: Package install
      run: |
        pip install .[tests,mysql,docs]
    - name: Mkdocs build
      run: |
        mkdocs build -d doc-build
    - name: Create config
      run: |
        grep -B 1000 -m 1 '^connection:$' src/rsm/resources/parser.cfg.yaml > tmp.cfg.yaml
        echo '  host: "127.0.0.1"' >> tmp.cfg.yaml
        echo '  port: "3306"' >> tmp.cfg.yaml
        echo '  user: "root"' >> tmp.cfg.yaml
        echo '  db: "integration_test"' >> tmp.cfg.yaml
        echo '  pw: "${{ secrets.MYSQL_ROOT }}"' >> tmp.cfg.yaml
    - name: Check DB ready
      run: |
        while ! mysqladmin ping --port 3306 --host=127.0.0.1 --password=${{ secrets.MYSQL_ROOT }} --silent; do
          sleep 1
        done
    - name: Setup table
      run: |
        mysql --user=root --password=${{ secrets.MYSQL_ROOT }} --port 3306 --host=127.0.0.1 --database=integration_test < tests/data/loader.ddl
    - name: Run test DB load
      run: |
        rsm to-db -c tmp.cfg.yaml -i tests/data/Input_74cols.xlsx -o tmp.result.csv
    - name: Tests and coverage file
      run: |
        pytest --cache-clear --cov=rsm . > pytest-coverage.txt
    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2
